"""empty message

Revision ID: e05b43862135
Revises: e8fb6ad15eb6
Create Date: 2019-05-04 06:30:44.617828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05b43862135'
down_revision = 'e8fb6ad15eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('filename', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_sample_filename'), 'sample', ['filename'], unique=False)
    op.drop_index('ix_sample_file_name', table_name='sample')
    op.drop_column('sample', 'file_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('file_name', sa.VARCHAR(length=128), nullable=True))
    op.create_index('ix_sample_file_name', 'sample', ['file_name'], unique=False)
    op.drop_index(op.f('ix_sample_filename'), table_name='sample')
    op.drop_column('sample', 'filename')
    # ### end Alembic commands ###
