"""empty message

Revision ID: e8fb6ad15eb6
Revises: 1281cc1d6122
Create Date: 2019-05-02 12:42:37.396015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fb6ad15eb6'
down_revision = '1281cc1d6122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('answer', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_sample_answer'), 'sample', ['answer'], unique=False)
    op.create_index(op.f('ix_sample_file_name'), 'sample', ['file_name'], unique=False)
    op.create_index(op.f('ix_sample_hash'), 'sample', ['hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sample_hash'), table_name='sample')
    op.drop_index(op.f('ix_sample_file_name'), table_name='sample')
    op.drop_index(op.f('ix_sample_answer'), table_name='sample')
    op.drop_column('sample', 'answer')
    # ### end Alembic commands ###
